#colors
BALL_WIDTH = .025
BALL_HEIGHT = BALL_WIDTH * 3 / 2
PAD_WIDTH = .015
PAD_HEIGHT = .2
HALF_PAD_WIDTH = PAD_WIDTH / 2
HALF_PAD_HEIGHT = PAD_HEIGHT / 2
WINNING_SCORE = 3
BOUNCE_SPEED_UP = 1.1
PADDLE_VEL=1.2
BALL_HORZ_RANGE = (0.2, 0.4)
BALL_VERT_RANGE = (0, 0.3)